version: "3.4"

services:
  customer-service:
    depends_on:
      - "customer_db"
    container_name: customer-service
    ports:
      - "5005:80"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ConnectionStrings:PostgresDb=server=customer_db;port=5432;database=DocumentManager;username=postgres;password=postgres;Pooling=true;
      - ASPNETCORE_ENVIRONMENT=Development

  customer_db:
    image: postgres:latest
    container_name: customer_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "1234:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/

volumes:
  customer_data:
